export const COUNTRY_CODES = [
    { code: "+93", country: "Afghanistan", isoCode: "af", digits: 9 },
    { code: "+355", country: "Albania", isoCode: "al", digits: 9 },
    { code: "+213", country: "Algeria", isoCode: "dz", digits: 9 },
    { code: "+376", country: "Andorra", isoCode: "ad", digits: 6 },
    { code: "+244", country: "Angola", isoCode: "ao", digits: 9 },
    { code: "+1", country: "Anguilla", isoCode: "ai", digits: 10 },
    { code: "+247", country: "Ascension Island", isoCode: "ac", digits: { min: 7, max: 10 } },
    { code: "+1", country: "American Samoa", isoCode: "as", digits: 10 },
    { code: "+1", country: "Antigua and Barbuda", isoCode: "ag", digits: 10 },
    { code: "+54", country: "Argentina", isoCode: "ar", digits: { min: 6, max: 8 } },
    { code: "+374", country: "Armenia", isoCode: "am", digits: 6 },
    { code: "+297", country: "Aruba", isoCode: "aw", digits: 7 },
    { code: "+61", country: "Australia", isoCode: "au", digits: 9 },
    { code: "+43", country: "Austria", isoCode: "at", digits: { min: 10, max: 11 } },
    { code: "+994", country: "Azerbaijan", isoCode: "az", digits: 9 },
    { code: "+1", country: "Bahamas", isoCode: "bs", digits: 10 },
    { code: "+973", country: "Bahrain", isoCode: "bh", digits: 8 },
    { code: "+1", country: "British Virgin Islands", isoCode: "vg", digits: 10 },
    { code: "+880", country: "Bangladesh", isoCode: "bd", digits: 10 },
    { code: "+1", country: "Barbados", isoCode: "bb", digits: 10 },
    { code: "+375", country: "Belarus", isoCode: "by", digits: 9 },
    { code: "+32", country: "Belgium", isoCode: "be", digits: 9 },
    { code: "+501", country: "Belize", isoCode: "bz", digits: 7 },
    { code: "+229", country: "Benin", isoCode: "bj", digits: 8 },
    { code: "+975", country: "Bhutan", isoCode: "bt", digits: 7 },
    { code: "+591", country: "Bolivia", isoCode: "bo", digits: 9 },
    { code: "+387", country: "Bosnia and Herzegovina", isoCode: "ba", digits: 8 },
    { code: "+267", country: "Botswana", isoCode: "bw", digits: 7 },
    { code: "+55", country: "Brazil", isoCode: "br", digits: 11 },
    { code: "+673", country: "Brunei", isoCode: "bn", digits: 7 },
    { code: "+359", country: "Bulgaria", isoCode: "bg", digits: 9 },
    { code: "+226", country: "Burkina Faso", isoCode: "bf", digits: 8 },
    { code: "+257", country: "Burundi", isoCode: "bi", digits: 8 },
    { code: "+855", country: "Cambodia", isoCode: "kh", digits: 9 },
    { code: "+237", country: "Cameroon", isoCode: "cm", digits: 9 },
    { code: "+1", country: "Canada", isoCode: "ca", digits: 10 },
    { code: "+238", country: "Cape Verde", isoCode: "cv", digits: 7 },
    { code: "+1", country: "Cayman Islands", isoCode: "ky", digits: 10 },
    { code: "+236", country: "Central African Republic", isoCode: "cf", digits: 8 },
    { code: "+235", country: "Chad", isoCode: "td", digits: 6 },
    { code: "+56", country: "Chile", isoCode: "cl", digits: 9 },
    { code: "+86", country: "China", isoCode: "cn", digits: 11 },
    { code: "+61", country: "Christmas Island", isoCode: "cx", digits: 9 },
    { code: "+61", country: "Cocos (Keeling) Islands", isoCode: "cc", digits: 10 },
    { code: "+682", country: "Cook Islands", isoCode: "ck", digits: 5 },
    { code: "+57", country: "Colombia", isoCode: "co", digits: 10 },
    { code: "+269", country: "Comoros", isoCode: "km", digits: 7 },
    { code: "+242", country: "Congo", isoCode: "cg", digits: 9 },
    { code: "+243", country: "Congo (DRC)", isoCode: "cd", digits: 7 },
    { code: "+506", country: "Costa Rica", isoCode: "cr", digits: 8 },
    { code: "+225", country: "Côte d'Ivoire", isoCode: "ci", digits: 8 },
    { code: "+385", country: "Croatia", isoCode: "hr", digits: 9 },
    { code: "+53", country: "Cuba", isoCode: "cu", digits: 8 },
    { code: "+357", country: "Cyprus", isoCode: "cy", digits: 8 },
    { code: "+420", country: "Czech Republic", isoCode: "cz", digits: 9 },
    { code: "+45", country: "Denmark", isoCode: "dk", digits: 8 },
    { code: "+246", country: "Diego Garcia", isoCode: "dg", digits: 7 },
    { code: "+253", country: "Djibouti", isoCode: "dj", digits: 10 },
    { code: "+1", country: "Dominica", isoCode: "dm", digits: 10 },
    { code: "+1", country: "Dominican Republic", isoCode: "do", digits: 10 },
    { code: "+593", country: "Ecuador", isoCode: "ec", digits: 9 },
    { code: "+20", country: "Egypt", isoCode: "eg", digits: 10 },
    { code: "+503", country: "El Salvador", isoCode: "sv", digits: 8 },
    { code: "+240", country: "Equatorial Guinea", isoCode: "gq", digits: 9 },
    { code: "+291", country: "Eritrea", isoCode: "er", digits: 7 },
    { code: "+372", country: "Estonia", isoCode: "ee", digits: 8 },
    { code: "+268", country: "Eswatini", isoCode: "sz", digits: 8 },
    { code: "+251", country: "Ethiopia", isoCode: "et", digits: 9 },
    { code: "+500", country: "Falkland Islands", isoCode: "fk", digits: 5 },
    { code: "+298", country: "Faroe Islands", isoCode: "fo", digits: 5 },
    { code: "+679", country: "Fiji", isoCode: "fj", digits: 7 },
    { code: "+358", country: "Finland", isoCode: "fi", digits: { min: 9, max: 11 } },
    { code: "+33", country: "France", isoCode: "fr", digits: 9 },
    { code: "+594", country: "French Guiana", isoCode: "gf", digits: 9 },
    { code: "+689", country: "French Polynesia", isoCode: "pf", digits: 8 },
    { code: "+241", country: "Gabon", isoCode: "ga", digits: 7 },
    { code: "+220", country: "Gambia", isoCode: "gm", digits: 7 },
    { code: "+995", country: "Georgia", isoCode: "ge", digits: 9 },
    { code: "+49", country: "Germany", isoCode: "de", digits: 10 },
    { code: "+233", country: "Ghana", isoCode: "gh", digits: 9 },
    { code: "+350", country: "Gibraltar", isoCode: "gi", digits: 8 },
    { code: "+30", country: "Greece", isoCode: "gr", digits: 10 },
    { code: "+299", country: "Greenland", isoCode: "gl", digits: 6 },
    { code: "+590", country: "Guadeloupe", isoCode: "gp", digits: 9 },
    { code: "+1", country: "Grenada", isoCode: "gd", digits: 10 },
    { code: "+1", country: "Guam", isoCode: "gu", digits: 10 },
    { code: "+502", country: "Guatemala", isoCode: "gt", digits: 8 },
    { code: "+224", country: "Guinea", isoCode: "gn", digits: 9 },
    { code: "+245", country: "Guinea-Bissau", isoCode: "gw", digits: 9 },
    { code: "+592", country: "Guyana", isoCode: "gy", digits: 7 },
    { code: "+509", country: "Haiti", isoCode: "ht", digits: 8 },
    { code: "+504", country: "Honduras", isoCode: "hn", digits: 8 },
    { code: "+852", country: "Hong Kong", isoCode: "hk", digits: 8 },
    { code: "+36", country: "Hungary", isoCode: "hu", digits: 9 },
    { code: "+354", country: "Iceland", isoCode: "is", digits: 7 },
    { code: "+91", country: "India", isoCode: "in", digits: 10 },
    { code: "+62", country: "Indonesia", isoCode: "id", digits: 11 },
    { code: "+98", country: "Iran", isoCode: "ir", digits: 11 },
    { code: "+964", country: "Iraq", isoCode: "iq", digits: 10 },
    { code: "+353", country: "Ireland", isoCode: "ie", digits: 9 },
    { code: "+44", country: "Isle of Man", isoCode: "im", digits: 10 },
    { code: "+972", country: "Israel", isoCode: "il", digits: 9 },
    { code: "+39", country: "Italy", isoCode: "it", digits: 10 },
    { code: "+1", country: "Jamaica", isoCode: "jm", digits: 10 },
    { code: "+81", country: "Japan", isoCode: "jp", digits: 10 },
    { code: "+44", country: "Jersey", isoCode: "je", digits: 10 },
    { code: "+962", country: "Jordan", isoCode: "jo", digits: { min: 8, max: 9 } },
    { code: "+7", country: "Kazakhstan", isoCode: "kz", digits: 10 },
    { code: "+254", country: "Kenya", isoCode: "ke", digits: 10 },
    { code: "+686", country: "Kiribati", isoCode: "ki", digits: 8 },
    { code: "+965", country: "Kuwait", isoCode: "kw", digits: 8 },
    { code: "+996", country: "Kyrgyzstan", isoCode: "kg", digits: 9 },
    { code: "+856", country: "Laos", isoCode: "la", digits: { min: 8, max: 9 } },
    { code: "+371", country: "Latvia", isoCode: "lv", digits: 8 },
    { code: "+961", country: "Lebanon", isoCode: "lb", digits: { min: 7, max: 8 } },
    { code: "+266", country: "Lesotho", isoCode: "ls", digits: 8 },
    { code: "+231", country: "Liberia", isoCode: "lr", digits: { min: 8, max: 9 } },
    { code: "+218", country: "Libya", isoCode: "ly", digits: 10 },
    { code: "+423", country: "Liechtenstein", isoCode: "li", digits: 7 },
    { code: "+370", country: "Lithuania", isoCode: "lt", digits: 8 },
    { code: "+352", country: "Luxembourg", isoCode: "lu", digits: 9 },
    { code: "+853", country: "Macau", isoCode: "mo", digits: 8 },
    { code: "+261", country: "Madagascar", isoCode: "mg", digits: 7 },
    { code: "+265", country: "Malawi", isoCode: "mw", digits: { min: 7, max: 9 } },
    { code: "+60", country: "Malaysia", isoCode: "my", digits: 7 },
    { code: "+960", country: "Maldives", isoCode: "mv", digits: 7 },
    { code: "+223", country: "Mali", isoCode: "ml", digits: 8 },
    { code: "+356", country: "Malta", isoCode: "mt", digits: 8 },
    { code: "+692", country: "Marshall Islands", isoCode: "mh", digits: 7 },
    { code: "+596", country: "Martinique", isoCode: "mq", digits: 9 },
    { code: "+222", country: "Mauritania", isoCode: "mr", digits: 8 },
    { code: "+230", country: "Mauritius", isoCode: "mu", digits: 8 },
    { code: "+262", country: "Mayotte", isoCode: "yt", digits: 9 },
    { code: "+52", country: "Mexico", isoCode: "mx", digits: 10 },
    { code: "+691", country: "Micronesia", isoCode: "fm", digits: 7 },
    { code: "+373", country: "Moldova", isoCode: "md", digits: 8 },
    { code: "+377", country: "Monaco", isoCode: "mc", digits: 8 },
    { code: "+976", country: "Mongolia", isoCode: "mn", digits: 8 },
    { code: "+382", country: "Montenegro", isoCode: "me", digits: 8 },
    { code: "+1", country: "Montserrat", isoCode: "ms", digits: 10 },
    { code: "+212", country: "Morocco", isoCode: "ma", digits: 9 },
    { code: "+258", country: "Mozambique", isoCode: "mz", digits: 12 },
    { code: "+95", country: "Myanmar", isoCode: "mm", digits: { min: 7, max: 10 } },
    { code: "+264", country: "Namibia", isoCode: "na", digits: 7 },
    { code: "+674", country: "Nauru", isoCode: "nr", digits: 7 },
    { code: "+977", country: "Nepal", isoCode: "np", digits: 10 },
    { code: "+31", country: "Netherlands", isoCode: "nl", digits: 9 },
    { code: "+599", country: "Netherlands Antilles", isoCode: "an", digits: 7 },
    { code: "+687", country: "New Caledonia", isoCode: "nc", digits: 6 },
    { code: "+64", country: "New Zealand", isoCode: "nz", digits: { min: 8, max: 9 } },
    { code: "+505", country: "Nicaragua", isoCode: "ni", digits: 8 },
    { code: "+227", country: "Niger", isoCode: "ne", digits: 8 },
    { code: "+234", country: "Nigeria", isoCode: "ng", digits: 10 },
    { code: "+683", country: "Niue", isoCode: "nu", digits: 4 },
    { code: "+672", country: "Norfolk Island", isoCode: "nf", digits: 6 },
    { code: "+850", country: "North Korea", isoCode: "kp", digits: { min: 4, max: 13 } },
    { code: "+1", country: "Northern Mariana Islands", isoCode: "mp", digits: 10 },
    { code: "+389", country: "North Macedonia", isoCode: "mk", digits: 8 },
    { code: "+47", country: "Norway", isoCode: "no", digits: 8 },
    { code: "+968", country: "Oman", isoCode: "om", digits: 8 },
    { code: "+92", country: "Pakistan", isoCode: "pk", digits: 10 },
    { code: "+680", country: "Palau", isoCode: "pw", digits: 7 },
    { code: "+970", country: "Palestine", isoCode: "ps", digits: 9 },
    { code: "+507", country: "Panama", isoCode: "pa", digits: 8 },
    { code: "+675", country: "Papua New Guinea", isoCode: "pg", digits: 8 },
    { code: "+595", country: "Paraguay", isoCode: "py", digits: 9 },
    { code: "+51", country: "Peru", isoCode: "pe", digits: 9 },
    { code: "+63", country: "Philippines", isoCode: "ph", digits: 10 },
    { code: "+870", country: "Pitcairn Islands", isoCode: "pn", digits: 9 },
    { code: "+48", country: "Poland", isoCode: "pl", digits: 9 },
    { code: "+351", country: "Portugal", isoCode: "pt", digits: 9 },
    { code: "+1", country: "Puerto Rico", isoCode: "pr", digits: 10 },
    { code: "+974", country: "Qatar", isoCode: "qa", digits: 8 },
    { code: "+40", country: "Romania", isoCode: "ro", digits: 10 },
    { code: "+262", country: "Reunion Island", isoCode: "re", digits: 10 },
    { code: "+7", country: "Russia", isoCode: "ru", digits: 10 },
    { code: "+250", country: "Rwanda", isoCode: "rw", digits: 9 },
    { code: "+590", country: "Saint Barthelemy", isoCode: "bl", digits: 9 },
    { code: "+290", country: "Saint Helena", isoCode: "sh", digits: 4 },
    { code: "+1", country: "Saint Kitts and Nevis", isoCode: "kn", digits: 10 },
    { code: "+1", country: "Saint Lucia", isoCode: "lc", digits: 10 },
    { code: "+590", country: "Saint Martin", isoCode: "mf", digits: 9 },
    { code: "+508", country: "Saint Pierre and Miquelon", isoCode: "pm", digits: 6 },
    { code: "+1", country: "Saint Vincent and the Grenadines", isoCode: "vc", digits: 10 },
    { code: "+685", country: "Samoa", isoCode: "ws", digits: { min: 5, max: 7 } },
    { code: "+378", country: "San Marino", isoCode: "sm", digits: 10 },
    { code: "+239", country: "Sao Tome and Principe", isoCode: "st", digits: 7 },
    { code: "+966", country: "Saudi Arabia", isoCode: "sa", digits: 9 },
    { code: "+221", country: "Senegal", isoCode: "sn", digits: 9 },
    { code: "+381", country: "Serbia", isoCode: "rs", digits: 9 },
    { code: "+248", country: "Seychelles", isoCode: "sc", digits: 7 },
    { code: "+232", country: "Sierra Leone", isoCode: "sl", digits: 8 },
    { code: "+65", country: "Singapore", isoCode: "sg", digits: 8 },
    { code: "+421", country: "Slovakia", isoCode: "sk", digits: 9 },
    { code: "+386", country: "Slovenia", isoCode: "si", digits: 9 },
    { code: "+677", country: "Solomon Islands", isoCode: "sb", digits: 7 },
    { code: "+252", country: "Somalia", isoCode: "so", digits: { min: 8, max: 9 } },
    { code: "+27", country: "South Africa", isoCode: "za", digits: 9 },
    { code: "+82", country: "South Korea", isoCode: "kr", digits: { min: 7, max: 8 } },
    { code: "+211", country: "South Sudan", isoCode: "ss", digits: 7 },
    { code: "+34", country: "Spain", isoCode: "es", digits: 9 },
    { code: "+94", country: "Sri Lanka", isoCode: "lk", digits: 7 },
    { code: "+249", country: "Sudan", isoCode: "sd", digits: 7 },
    { code: "+597", country: "Suriname", isoCode: "sr", digits: { min: 6, max: 7 } },
    { code: "+1", country: "Sint Maarten", isoCode: "sx", digits: 10 },
    { code: "+46", country: "Sweden", isoCode: "se", digits: 7 },
    { code: "+47", country: "Svalbard", isoCode: "sj", digits: 8 },
    { code: "+41", country: "Switzerland", isoCode: "ch", digits: 9 },
    { code: "+963", country: "Syria", isoCode: "sy", digits: { min: 7, max: 10 } },
    { code: "+886", country: "Taiwan", isoCode: "tw", digits: 9 },
    { code: "+992", country: "Tajikistan", isoCode: "tj", digits: 9 },
    { code: "+255", country: "Tanzania", isoCode: "tz", digits: 7 },
    { code: "+66", country: "Thailand", isoCode: "th", digits: 9 },
    { code: "+670", country: "Timor-Leste", isoCode: "tl", digits: 7 },
    { code: "+228", country: "Togo", isoCode: "tg", digits: 8 },
    { code: "+690", country: "Tokelau", isoCode: "tk", digits: 5 },
    { code: "+676", country: "Tonga", isoCode: "to", digits: 5 },
    { code: "+1", country: "Trinidad and Tobago", isoCode: "tt", digits: 10 },
    { code: "+216", country: "Tunisia", isoCode: "tn", digits: 8 },
    { code: "+90", country: "Turkey", isoCode: "tr", digits: 10 },
    { code: "+993", country: "Turkmenistan", isoCode: "tm", digits: 8 },
    { code: "+1", country: "Turks and Caicos Islands", isoCode: "tc", digits: 10 },
    { code: "+1", country: "Tuvalu", isoCode: "tv", digits: 10 },
    { code: "+256", country: "Uganda", isoCode: "ug", digits: 7 },
    { code: "+380", country: "Ukraine", isoCode: "ua", digits: 9 },
    { code: "+971", country: "United Arab Emirates", isoCode: "ae", digits: 9 },
    { code: "+44", country: "United Kingdom", isoCode: "gb", digits: 10 },
    { code: "+1", country: "United States", isoCode: "us", digits: 10 },
    { code: "+1", country: "US Virgin Islands", isoCode: "vi", digits: 10 },
    { code: "+598", country: "Uruguay", isoCode: "uy", digits: 8 },
    { code: "+998", country: "Uzbekistan", isoCode: "uz", digits: 9 },
    { code: "+678", country: "Vanuatu", isoCode: "vu", digits: 5 },
    { code: "+379", country: "Vatican City (Holy See)", isoCode: "va", digits: 10 },
    { code: "+58", country: "Venezuela", isoCode: "ve", digits: 7 },
    { code: "+84", country: "Vietnam", isoCode: "vn", digits: 9 },
    { code: "+681", country: "Wallis and Futuna", isoCode: "wf", digits: 6 },
    { code: "+212", country: "Western Sahara", isoCode: "eh", digits: 9 },
    { code: "+967", country: "Yemen", isoCode: "ye", digits: 9 },
    { code: "+260", country: "Zambia", isoCode: "zm", digits: 9 },
    { code: "+263", country: "Zimbabwe", isoCode: "zw", digits: 9 },
];

export const DEFAULT_COUNTRY_CODE = "+968";
export const DEFAULT_ISO_CODE = "om";

export const getFlagImageUrl = (isoCode) => {
    return `https://flagcdn.com/w20/${isoCode.toLowerCase()}.png`;
};

export const getCountryCodeByCode = (code) => {
    return COUNTRY_CODES.find((cc) => cc.code === code) || COUNTRY_CODES[0];
};

export const getCountryCodeByIsoCode = (isoCode) => {
    if (!isoCode) return null;
    return COUNTRY_CODES.find((cc) => cc.isoCode === isoCode.toLowerCase()) || null;
};

export const formatPhoneNumberForDisplay = (phone, isoCode) => {
    if (!phone) return phone || "";

    if (phone.startsWith("+")) {
        return phone;
    }

    if (isoCode) {
        const country = getCountryCodeByIsoCode(isoCode);
        if (country) {
            return `${country.code}${phone}`;
        }
    }

    return phone;
};

export const validatePhoneNumber = (phone, isoCode) => {
    if (!phone) return false;

    const country = getCountryCodeByIsoCode(isoCode);
    if (!country) return false;

    const digits = country.digits;
    const phoneLength = phone.replace(/\D/g, '').length;

    if (typeof digits === 'number') {
        return phoneLength === digits;
    } else if (typeof digits === 'object' && digits.min && digits.max) {
        return phoneLength >= digits.min && phoneLength <= digits.max;
    }

    return true;
};
